char parameters_string[]=
"// Parameters for the Fenton-Karma model\n"
"#define u_c 0.13                                 // (dimensionless)\n"
"#define u_v 0.04                                 // (dimensionless)\n"
"#define tau_d 0.388                              // Fast_inward_current (ms)\n"
"#define tau_v1_minus 7.6                           // Fast_inward_current_v_gate (ms)\n"
"#define tau_v2_minus 8.8                           // Fast_inward_current_v_gate (ms)\n"
"#define tau_v_plus 3.324                          // Fast_inward_current_v_gate (ms)\n"
"#define tau_0 8.2                                  // Slow_outward_current (ms)\n"
"#define tau_r 33.264                              // Slow_outward_current (ms)\n"
"#define tau_si 29.0                                // Slow_inward_current (ms)\n"
"#define u_csi 0.54                               // Slow_inward_current (dimensionless)\n"
"#define k_fk 15.0                                     // Slow_inward_current (dimensionless)\n"
"#define tau_w_minus 68.0                           // Slow_inward_current_w_gate (ms)\n"
"#define tau_w_plus 399.99999999999994                           // Slow_inward_current_w_gate (ms)\n"
"\n"
"#define Du 1.0e-3\n"
"#define Dv 1.0e-5\n"
"#define Dw 1.0e-5\n"
"\n"
"// Parameter in smoothed step function\n"
"#define ksm 100.0\n"
"\n"
"constexpr double h = 0.035; // spatial mesh width\n"
"constexpr int nvar = 3;\n"
"\n"
"\n"
"// File written by interpolate_fk_parameters.py\n"
"#define BLOCK_SIZE_X 16\n"
"#define BLOCK_SIZE_Y 16\n"
"#define BLOCK_SIZE_XY ((BLOCK_SIZE_X)*(BLOCK_SIZE_Y))\n"
;
